# results_folder_path: "./results/2023_05_20_run"

config_name: "ModelV1_BCELoss_Adam"
batch_size: 64
epochs: 100
n_initializations: 5
num_workers: 4
debug: false

et_range_idx: [0]
eta_range_idx: [1]

loss_function:
  module: "torch.nn"
  object_name: "BCELoss"

optimizer_function:
  module: "torch.optim"
  object_name: "Adam"
  parameters:
    lr: 0.001

kFold:
  module: "sklearn.model_selection"
  object_name: "StratifiedKFold"
  parameters:
    n_splits: 10
    random_state: 42
    shuffle: True

model:
  module: "src.Models.egamma.ModelV1"
  object_name: "ModelV1"
  parameters:
    input_dim: 50

dataset:
  module: "src.Core.Datasets.EgammaNpzDataset"
  object_name: "EgammaNpzDataset"
  parameters:
    drive_path: "/eos/user/j/jlieberm/photonRinger/datasets/notIso"
    startswith: "mc23_13TeV"
    endswith: ".npz"
    percentage: 0.5
